version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_ROOT_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - 5433:5432
    networks:
      - weather
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - db
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 9082:9082
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/weatherhost
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    networks:
      - weather

networks:
  weather:

volumes:
  db:
    driver: local
