apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
type: Opaque
data:
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtYXBwLWNsdXN0ZXJpcDo1NDMyL3dlYXRoZXJob3N0
#jdbc:postgresql://postgres-app-clusterip:5432/weatherhost

