spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/weatherhost
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        open-in-view: false
location: Minsk
rapidapi:
    key: 3feeebc156msh11bbe10b811e416p169342jsn0b2e9c5f87a8
    host: weatherapi-com.p.rapidapi.com