spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/weatherhost
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        open-in-view: false
